name: CommandBlock
author: TastischerGamer
version: 1.1
main: me.TastischerGamer.CommandBlock.main.CommandBlockPlugin

commands:
   cbconfig:
      description: Config neu laden
      Usage: /cbconfig
      
   commandblock:
      description: Blockiere / entblockiere Commands!
      Usage: /commandblock help
      aliases: [cblock]